### ISSUE TITLE
阿里云AK问题

### ISSUE THREAD

**Issue by SaarChaffee** [wandou-cc/exclusive-translation#1]
我想问一下，为什么我用子账号的AK会弹出errorcode，说我AK错误，但是用主账号的AK就没有问题

**Comment by wandou-cc** [comment]
你先使用主帐号的 子帐号的我 明天发布个 小版本 改一下

**Comment by SaarChaffee** [comment]
十分感谢，虽然不改也没有大问题我继续用主账号的就是

**Comment by SaarChaffee** [comment]
只是刚好遇到了这问题哈哈哈

**Comment by wandou-cc** [comment]
没事 感谢提醒

**Comment by wandou-cc** [comment]
需要在 RAM 访问控制  - 用户 添加权限 给 子用户 添加权限 即可
![image](https://user-images.githubusercontent.com/90685660/146899880-0e75e743-196f-449a-9546-64c4f2fe5c06.png)

**Comment by SaarChaffee** [comment]
我有给的，一开始给只读所有资源不行，之后我就给了管理所有资源，还是不行

**Comment by SaarChaffee** [comment]
![image](https://user-images.githubusercontent.com/53519746/146901243-7e410323-a394-48b3-9836-b56961d6f79c.png)

**Comment by wandou-cc** [comment]
vscode 配置 截图我看一下

**Comment by SaarChaffee** [comment]
哦哦我的问题，，不知道什么时候把英译的目标语音给删掉了

**Comment by SaarChaffee** [comment]
![image](https://user-images.githubusercontent.com/53519746/146903074-545ecf36-73de-49e8-ac80-a07b46dc6f88.png)

**Comment by SaarChaffee** [comment]
现在就正常了

**Comment by wandou-cc** [comment]
好的 下个 版本 我加个 默认值

**Comment by SaarChaffee** [comment]
谢谢大佬

**Comment by wandou-cc** [comment]
客气
