### ISSUE TITLE
vscode如何修改快捷键？

### ISSUE THREAD

**Issue by 11003** [wandou-cc/exclusive-translation#3]
![image](https://github.com/wandou-cc/exclusive-translation/assets/35055270/4ba8be77-9c6f-4ec4-8ccc-33066426148f)
大佬没有看到可以设置快捷键呀

**Comment by wandou-cc** [comment]
快捷键不在这里设置[image: image.png]

Sonder ***@***.***> 于2023年12月12日周二 16:28写道：

**Comment by wandou-cc** [comment]
哦 对了 google用不了 提醒一下

超陈 ***@***.***> 于2023年12月15日周五 11:28写道：
